apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo-db
          image: mongo:3
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: config
              mountPath: /config
            - name: mongo-credentials
              mountPath: /etc/mongo-credentials
            - name: data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
      volumes:
        - name: mongo-credentials
          secret:
            secretName: mongo-secret
        - name: data
          persistentVolumeClaim:
            claimName: mongo-pv-claim
        - name: config
          configMap:
            name: mongo-config