version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq_container"
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network
  order-service:
    image: fitrarizki/order-service:latest
    depends_on:
      - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
    networks:
      - rabbitmq_network
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
  shipping-service:
    image: fitrarizki/shipping-service:latest
    depends_on:
      - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
    networks:
      - rabbitmq_network
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
networks:
  rabbitmq_network:
    driver: bridge